### PR TITLE
Add support for offset

### PR DESCRIPTION
**Pull request by joaquinwojcik**
Add some basic support for offset as requested on #48 

Usage:
```javascript
Toastify({
  text: "This is a toast with offset",
  offset: {
    x: 50, // horizontal axis - can be a number or a string indicating unity. eg: '2em'
    y: 10 // vertical axis - can be a number or a string indicating unity. eg: '2em'
  },
}).showToast();
```
Toast will be pushed 50px from right in x axis and 10px from top in y axis.

Example:
image

If `position` is equals to `left`, it will be pushed from left.
If `gravity` is equals to `bottom`, it will be pushed from bottom.

Example:
image

Also updated the docs.

### CODE REVIEW

**Comment by lwxbr** [comment]
PING @apvarun

**Comment by apvarun** [comment]
@joaquinwojcik @Tadaz Appreciate your pull requests. Both of you have PR's for similar feature.

**My opinion:** I prefer the API from #49 but also include offset between toasts like in #45 
Would like to know your use cases too so that we can decide on one common way of adding offsets.

**Comment by aconital** [comment]
@apvarun any update on this?

**Comment by apvarun** [comment]
@aconital Do you mind contributing your thoughts on which of the implementation is better suited for this use-case? #49 or #45

**Comment by aconital** [comment]
@apvarun I personally prefer #49 for offset.

**Comment by joaquinwojcik** [comment]
PING @apvarun 

I've updated the README. I thinks its ready to merge.

**Comment by apvarun** [comment]
Version 1.9.0 contains your changes @joaquinwojcik 
https://www.npmjs.com/package/toastify-js/v/1.9.0

**Pull request merged**
