### PR TITLE
Update the close icon

### PR DESCRIPTION
**Pull request by NKjoep**
Hello 👋 

First, congrats for this project. It's very well though. 👍 

Second, I would like to suggest to consider updating the close symbol with a more html-friendly one.
This way its color could be also styled.

### CODE REVIEW

**Comment by NKjoep** [comment]
cc @apvarun

**Comment by apvarun** [comment]
Hi @NKjoep, the &times; close icon is much lighter in weight than the &#10006; icon. The reason for choosing it is to be clearly visible when displayed.

Also, it is possible to style &#10006; icon as well with a different color of your choice.

**Comment by NKjoep** [comment]
Uhm, actually you are right:

image

Well, nevermind then :)

**Comment by lurkasf** [comment]
Just for someone looking for options, i found that (for me) this: ✕  is the better option. Because it's bigger than the × and not too thick as the default ✖. 
I'm using the ✕ with `font-weight: bolder;`
Furthermore, to change the icon i'm using `toast.toastElement.querySelector('.toast-close').textContent = '✕';` right after the `.showToast()` call. 
That's it, bye.

**Comment by lurkasf** [comment]
Just for someone looking for options, i found that (for me) this: ✕  is the better option. Because it's bigger than the × and not too thick as the ✖. 
I'm using the ✕ with `font-weight: bolder;`
Furthermore, to change the icon i'm using `toast.toastElement.querySelector('.toast-close').textContent = '✕';` right after the `.showToast()` call. 
That's it, bye.

**Pull request closed without merging**
